-- 992 stickers seeded from stickers_album_final.csv
insert into stickers (id, section_code, section_name, section_order, num_in_section, label, type) values
('0','00','Panini',1,0,'Panini Logo','special'),
('FWC1','FWC','Tournament',2,1,'Official Emblem','opening'),
('FWC2','FWC','Tournament',2,2,'Official Emblem','opening'),
('FWC3','FWC','Tournament',2,3,'Official Mascots','opening'),
('FWC4','FWC','Tournament',2,4,'Official Slogan','opening'),
('FWC5','FWC','Tournament',2,5,'Official Ball','opening'),
('FWC6','FWC','Tournament',2,6,'Canada','opening'),
('FWC7','FWC','Tournament',2,7,'Mexico','opening'),
('FWC8','FWC','Tournament',2,8,'USA','opening'),
('FWC9','FWC','Tournament',2,9,'Italy 1934','history'),
('FWC10','FWC','Tournament',2,10,'Uruguay 1950','history'),
('FWC11','FWC','Tournament',2,11,'West Germany 1954','history'),
('FWC12','FWC','Tournament',2,12,'Brazil 1962','history'),
('FWC13','FWC','Tournament',2,13,'West Germany 1974','history'),
('FWC14','FWC','Tournament',2,14,'Argentina 1986','history'),
('FWC15','FWC','Tournament',2,15,'Brazil 1994','history'),
('FWC16','FWC','Tournament',2,16,'Brazil 2002','history'),
('FWC17','FWC','Tournament',2,17,'Italy 2006','history'),
('FWC18','FWC','Tournament',2,18,'Germany 2014','history'),
('FWC19','FWC','Tournament',2,19,'Argentina 2022','history'),
('MEX1','MEX','Mexico',3,1,'Emblem','crest'),
('MEX2','MEX','Mexico',3,2,'Luis Malagón','player'),
('MEX3','MEX','Mexico',3,3,'Johan Vasquez','player'),
('MEX4','MEX','Mexico',3,4,'Jorge Sánchez','player'),
('MEX5','MEX','Mexico',3,5,'Cesar Montes','player'),
('MEX6','MEX','Mexico',3,6,'Jesus Gallardo','player'),
('MEX7','MEX','Mexico',3,7,'Israel Reyes','player'),
('MEX8','MEX','Mexico',3,8,'Diego Lainez','player'),
('MEX9','MEX','Mexico',3,9,'Carlos Rodriguez','player'),
('MEX10','MEX','Mexico',3,10,'Edson Alvarez','player'),
('MEX11','MEX','Mexico',3,11,'Orbelin Pineda','player'),
('MEX12','MEX','Mexico',3,12,'Marcel Ruiz','player'),
('MEX13','MEX','Mexico',3,13,'Team Photo','photo'),
('MEX14','MEX','Mexico',3,14,'Érick Sánchez','player'),
('MEX15','MEX','Mexico',3,15,'Hirving Lozano','player'),
('MEX16','MEX','Mexico',3,16,'Santiago Giménez','player'),
('MEX17','MEX','Mexico',3,17,'Raúl Jiménez','player'),
('MEX18','MEX','Mexico',3,18,'Alexis Vega','player'),
('MEX19','MEX','Mexico',3,19,'Roberto Alvarado','player'),
('MEX20','MEX','Mexico',3,20,'Cesar Huerta','player'),
('RSA1','RSA','South Africa',4,1,'Emblem','crest'),
('RSA2','RSA','South Africa',4,2,'Ronwen Williams','player'),
('RSA3','RSA','South Africa',4,3,'Sipho Chaine','player'),
('RSA4','RSA','South Africa',4,4,'Aubrey Modiba','player'),
('RSA5','RSA','South Africa',4,5,'Samukele Kabini','player'),
('RSA6','RSA','South Africa',4,6,'Mbekezeli Mbokazi','player'),
('RSA7','RSA','South Africa',4,7,'Khulumani Ndamane','player'),
('RSA8','RSA','South Africa',4,8,'Siyabonga Ngezana','player'),
('RSA9','RSA','South Africa',4,9,'Khuliso Mudau','player'),
('RSA10','RSA','South Africa',4,10,'Nkosinathi Sibisi','player'),
('RSA11','RSA','South Africa',4,11,'Teboho Mokoena','player'),
('RSA12','RSA','South Africa',4,12,'Thalente Mbatha','player'),
('RSA13','RSA','South Africa',4,13,'Team Photo','photo'),
('RSA14','RSA','South Africa',4,14,'Bathusi Aubaas','player'),
('RSA15','RSA','South Africa',4,15,'Yaya Sithole','player'),
('RSA16','RSA','South Africa',4,16,'Sipho Mbule','player'),
('RSA17','RSA','South Africa',4,17,'Lyle Foster','player'),
('RSA18','RSA','South Africa',4,18,'Iqraam Rayners','player'),
('RSA19','RSA','South Africa',4,19,'Mohau Nkota','player'),
('RSA20','RSA','South Africa',4,20,'Oswin Appollis','player'),
('KOR1','KOR','South Korea',5,1,'Emblem','crest'),
('KOR2','KOR','South Korea',5,2,'Hyeon-woo Jo','player'),
('KOR3','KOR','South Korea',5,3,'Seung-Gyu Kim','player'),
('KOR4','KOR','South Korea',5,4,'Min-jae Kim','player'),
('KOR5','KOR','South Korea',5,5,'Yu-min Cho','player'),
('KOR6','KOR','South Korea',5,6,'Young-woo Seol','player'),
('KOR7','KOR','South Korea',5,7,'Han-beom Lee','player'),
('KOR8','KOR','South Korea',5,8,'Tae-seok Lee','player'),
('KOR9','KOR','South Korea',5,9,'Myung-jae Lee','player'),
('KOR10','KOR','South Korea',5,10,'Jae-sung Lee','player'),
('KOR11','KOR','South Korea',5,11,'In-beom Hwang','player'),
('KOR12','KOR','South Korea',5,12,'Kang-in Lee','player'),
('KOR13','KOR','South Korea',5,13,'Team Photo','photo'),
('KOR14','KOR','South Korea',5,14,'Seung-ho Paik','player'),
('KOR15','KOR','South Korea',5,15,'Jens Castrop','player'),
('KOR16','KOR','South Korea',5,16,'Dongg-yeong Lee','player'),
('KOR17','KOR','South Korea',5,17,'Gue-sung Cho','player'),
('KOR18','KOR','South Korea',5,18,'Heung-min Son','player'),
('KOR19','KOR','South Korea',5,19,'Hee-chan Hwang','player'),
('KOR20','KOR','South Korea',5,20,'Hyeon-Gyu Oh','player'),
('CZE1','CZE','Czechia',6,1,'Emblem','crest'),
('CZE2','CZE','Czechia',6,2,'Matej Kovar','player'),
('CZE3','CZE','Czechia',6,3,'Jindrich Stanek','player'),
('CZE4','CZE','Czechia',6,4,'Ladislav Krejci','player'),
('CZE5','CZE','Czechia',6,5,'Vladimir Coufal','player'),
('CZE6','CZE','Czechia',6,6,'Jaroslav Zeleny','player'),
('CZE7','CZE','Czechia',6,7,'Tomas Holes','player'),
('CZE8','CZE','Czechia',6,8,'David Zima','player'),
('CZE9','CZE','Czechia',6,9,'Michal Sadilek','player'),
('CZE10','CZE','Czechia',6,10,'Lukas Provod','player'),
('CZE11','CZE','Czechia',6,11,'Lukas Cerv','player'),
('CZE12','CZE','Czechia',6,12,'Tomas Soucek','player'),
('CZE13','CZE','Czechia',6,13,'Team Photo','photo'),
('CZE14','CZE','Czechia',6,14,'Pavel Sulc','player'),
('CZE15','CZE','Czechia',6,15,'Matej Vydra','player'),
('CZE16','CZE','Czechia',6,16,'Vasil Kusej','player'),
('CZE17','CZE','Czechia',6,17,'Tomas Chory','player'),
('CZE18','CZE','Czechia',6,18,'Vaclav Cerny','player'),
('CZE19','CZE','Czechia',6,19,'Adam Hlozek','player'),
('CZE20','CZE','Czechia',6,20,'Patrik Schick','player'),
('CAN1','CAN','Canada',7,1,'Emblem','crest'),
('CAN2','CAN','Canada',7,2,'Dayne St.Clair','player'),
('CAN3','CAN','Canada',7,3,'Alphonso Davies','player'),
('CAN4','CAN','Canada',7,4,'Alistair Johnston','player'),
('CAN5','CAN','Canada',7,5,'Samuel Adekugbe','player'),
('CAN6','CAN','Canada',7,6,'Richie Laryea','player'),
('CAN7','CAN','Canada',7,7,'Derek Cornelius','player'),
('CAN8','CAN','Canada',7,8,'Moïse Bombito','player'),
('CAN9','CAN','Canada',7,9,'Kamal Miller','player'),
('CAN10','CAN','Canada',7,10,'Stephen Eustáquio','player'),
('CAN11','CAN','Canada',7,11,'Ismaël Koné','player'),
('CAN12','CAN','Canada',7,12,'Jonathan Osorio','player'),
('CAN13','CAN','Canada',7,13,'Team Photo','photo'),
('CAN14','CAN','Canada',7,14,'Jacob Shaffelburg','player'),
('CAN15','CAN','Canada',7,15,'Mathieu Choinière','player'),
('CAN16','CAN','Canada',7,16,'Niko Sigur','player'),
('CAN17','CAN','Canada',7,17,'Tajon Buchanan','player'),
('CAN18','CAN','Canada',7,18,'Liam Millar','player'),
('CAN19','CAN','Canada',7,19,'Cyle Larin','player'),
('CAN20','CAN','Canada',7,20,'Jonathan David','player'),
('BIH1','BIH','Bosnia and Herzegovina',8,1,'Emblem','crest'),
('BIH2','BIH','Bosnia and Herzegovina',8,2,'Nikola Vasilj','player'),
('BIH3','BIH','Bosnia and Herzegovina',8,3,'Amer Dedic','player'),
('BIH4','BIH','Bosnia and Herzegovina',8,4,'Sead Kolasinac','player'),
('BIH5','BIH','Bosnia and Herzegovina',8,5,'Tarik Muharemovic','player'),
('BIH6','BIH','Bosnia and Herzegovina',8,6,'Nihad Mujakic','player'),
('BIH7','BIH','Bosnia and Herzegovina',8,7,'Nikola Katic','player'),
('BIH8','BIH','Bosnia and Herzegovina',8,8,'Amir Hadziahmetovic','player'),
('BIH9','BIH','Bosnia and Herzegovina',8,9,'Benjamin Tahirovic','player'),
('BIH10','BIH','Bosnia and Herzegovina',8,10,'Armin Gigovic','player'),
('BIH11','BIH','Bosnia and Herzegovina',8,11,'Ivan Sunjic','player'),
('BIH12','BIH','Bosnia and Herzegovina',8,12,'Ivan Basic','player'),
('BIH13','BIH','Bosnia and Herzegovina',8,13,'Team Photo','photo'),
('BIH14','BIH','Bosnia and Herzegovina',8,14,'Dzenis Burnic','player'),
('BIH15','BIH','Bosnia and Herzegovina',8,15,'Esmir Bajraktarevic','player'),
('BIH16','BIH','Bosnia and Herzegovina',8,16,'Amar Memic','player'),
('BIH17','BIH','Bosnia and Herzegovina',8,17,'Ermedin Demirovic','player'),
('BIH18','BIH','Bosnia and Herzegovina',8,18,'Edin Dzeko','player'),
('BIH19','BIH','Bosnia and Herzegovina',8,19,'Samed Bazdar','player'),
('BIH20','BIH','Bosnia and Herzegovina',8,20,'Haris Tabakovic','player'),
('QAT1','QAT','Qatar',9,1,'Emblem','crest'),
('QAT2','QAT','Qatar',9,2,'Meshaal Barsham','player'),
('QAT3','QAT','Qatar',9,3,'Sultan Albrake','player'),
('QAT4','QAT','Qatar',9,4,'Lucas Mendes','player'),
('QAT5','QAT','Qatar',9,5,'Homam Ahmed','player'),
('QAT6','QAT','Qatar',9,6,'Boualem Khoukhi','player'),
('QAT7','QAT','Qatar',9,7,'Pedro Miguel','player'),
('QAT8','QAT','Qatar',9,8,'Tarek Salman','player'),
('QAT9','QAT','Qatar',9,9,'Mohamed Al-Mannai','player'),
('QAT10','QAT','Qatar',9,10,'Karim Boudiaf','player'),
('QAT11','QAT','Qatar',9,11,'Assim Madibo','player'),
('QAT12','QAT','Qatar',9,12,'Ahmed Fatehi','player'),
('QAT13','QAT','Qatar',9,13,'Team Photo','photo'),
('QAT14','QAT','Qatar',9,14,'Mohammed Waad','player'),
('QAT15','QAT','Qatar',9,15,'Abdulaziz Hatem','player'),
('QAT16','QAT','Qatar',9,16,'Hassan Al-Haydos','player'),
('QAT17','QAT','Qatar',9,17,'Edmilson Junior','player'),
('QAT18','QAT','Qatar',9,18,'Akram Hassan Afif','player'),
('QAT19','QAT','Qatar',9,19,'Ahmed Al Ganehi','player'),
('QAT20','QAT','Qatar',9,20,'Almoez Ali','player'),
('SUI1','SUI','Switzerland',10,1,'Emblem','crest'),
('SUI2','SUI','Switzerland',10,2,'Gregor Kobel','player'),
('SUI3','SUI','Switzerland',10,3,'Yvon Mvogo','player'),
('SUI4','SUI','Switzerland',10,4,'Manuel Akanji','player'),
('SUI5','SUI','Switzerland',10,5,'Ricardo Rodriguez','player'),
('SUI6','SUI','Switzerland',10,6,'Nico Elvedi','player'),
('SUI7','SUI','Switzerland',10,7,'Aurèle Amenda','player'),
('SUI8','SUI','Switzerland',10,8,'Silvan Widmer','player'),
('SUI9','SUI','Switzerland',10,9,'Granit Xhaka','player'),
('SUI10','SUI','Switzerland',10,10,'Denis Zakaria','player'),
('SUI11','SUI','Switzerland',10,11,'Remo Freuler','player'),
('SUI12','SUI','Switzerland',10,12,'Fabian Rieder','player'),
('SUI13','SUI','Switzerland',10,13,'Team Photo','photo'),
('SUI14','SUI','Switzerland',10,14,'Ardon Jashari','player'),
('SUI15','SUI','Switzerland',10,15,'Johan Manzambi','player'),
('SUI16','SUI','Switzerland',10,16,'Michel Aebischer','player'),
('SUI17','SUI','Switzerland',10,17,'Breel Embolo','player'),
('SUI18','SUI','Switzerland',10,18,'Ruben Vargas','player'),
('SUI19','SUI','Switzerland',10,19,'Dan Ndoye','player'),
('SUI20','SUI','Switzerland',10,20,'Zeki Amdouni','player'),
('BRA1','BRA','Brazil',11,1,'Emblem','crest'),
('BRA2','BRA','Brazil',11,2,'Alisson','player'),
('BRA3','BRA','Brazil',11,3,'Bento','player'),
('BRA4','BRA','Brazil',11,4,'Marquinhos','player'),
('BRA5','BRA','Brazil',11,5,'Éder Militão','player'),
('BRA6','BRA','Brazil',11,6,'Gabriel Magalhães','player'),
('BRA7','BRA','Brazil',11,7,'Danilo','player'),
('BRA8','BRA','Brazil',11,8,'Wesley','player'),
('BRA9','BRA','Brazil',11,9,'Lucas Paquetá','player'),
('BRA10','BRA','Brazil',11,10,'Casemiro','player'),
('BRA11','BRA','Brazil',11,11,'Bruno Guimarães','player'),
('BRA12','BRA','Brazil',11,12,'Luiz Henrique','player'),
('BRA13','BRA','Brazil',11,13,'Team Photo','photo'),
('BRA14','BRA','Brazil',11,14,'Vinicius Júnior','player'),
('BRA15','BRA','Brazil',11,15,'Rodrygo','player'),
('BRA16','BRA','Brazil',11,16,'João Pedro','player'),
('BRA17','BRA','Brazil',11,17,'Matheus Cunha','player'),
('BRA18','BRA','Brazil',11,18,'Gabriel Martinelli','player'),
('BRA19','BRA','Brazil',11,19,'Raphinha','player'),
('BRA20','BRA','Brazil',11,20,'Estévão','player'),
('MAR1','MAR','Morocco',12,1,'Emblem','crest'),
('MAR2','MAR','Morocco',12,2,'Yassine Bounou','player'),
('MAR3','MAR','Morocco',12,3,'Munir El Kajoui','player'),
('MAR4','MAR','Morocco',12,4,'Achraf Hakimi','player'),
('MAR5','MAR','Morocco',12,5,'Noussair Mazraoui','player'),
('MAR6','MAR','Morocco',12,6,'Nayef Aguerd','player'),
('MAR7','MAR','Morocco',12,7,'Romain Saïss','player'),
('MAR8','MAR','Morocco',12,8,'Jawad El Yamiq','player'),
('MAR9','MAR','Morocco',12,9,'Adam Masina','player'),
('MAR10','MAR','Morocco',12,10,'Sofyan Amrabat','player'),
('MAR11','MAR','Morocco',12,11,'Azzedine Ounahi','player'),
('MAR12','MAR','Morocco',12,12,'Eliesse Ben Seghir','player'),
('MAR13','MAR','Morocco',12,13,'Team Photo','photo'),
('MAR14','MAR','Morocco',12,14,'Bilal El Khannouss','player'),
('MAR15','MAR','Morocco',12,15,'Ismael Saibari','player'),
('MAR16','MAR','Morocco',12,16,'Youssef En-Nesyri','player'),
('MAR17','MAR','Morocco',12,17,'Abde Ezzalzouli','player'),
('MAR18','MAR','Morocco',12,18,'Soufiane Rahimi','player'),
('MAR19','MAR','Morocco',12,19,'Brahim Diaz','player'),
('MAR20','MAR','Morocco',12,20,'Ayoub El Kaabi','player'),
('HAI1','HAI','Haiti',13,1,'Emblem','crest'),
('HAI2','HAI','Haiti',13,2,'Johny Placide','player'),
('HAI3','HAI','Haiti',13,3,'Carlens Arcus','player'),
('HAI4','HAI','Haiti',13,4,'Martin Expérience','player'),
('HAI5','HAI','Haiti',13,5,'Jean-Kevin Duverne','player'),
('HAI6','HAI','Haiti',13,6,'Ricardo Adé','player'),
('HAI7','HAI','Haiti',13,7,'Duke Lacroix','player'),
('HAI8','HAI','Haiti',13,8,'Garven Metusala','player'),
('HAI9','HAI','Haiti',13,9,'Hannes Delcroix','player'),
('HAI10','HAI','Haiti',13,10,'Leverton Pierre','player'),
('HAI11','HAI','Haiti',13,11,'Danley Jean Jacques','player'),
('HAI12','HAI','Haiti',13,12,'Jean-Ricner Bellegarde','player'),
('HAI13','HAI','Haiti',13,13,'Team Photo','photo'),
('HAI14','HAI','Haiti',13,14,'Christopher Attys','player'),
('HAI15','HAI','Haiti',13,15,'Derrick Etienne Jr','player'),
('HAI16','HAI','Haiti',13,16,'Josue Casimir','player'),
('HAI17','HAI','Haiti',13,17,'Ruben Providence','player'),
('HAI18','HAI','Haiti',13,18,'Duckens Nazon','player'),
('HAI19','HAI','Haiti',13,19,'Louicius Deedson','player'),
('HAI20','HAI','Haiti',13,20,'Frantzdy Pierrot','player'),
('SCO1','SCO','Scotland',14,1,'Emblem','crest'),
('SCO2','SCO','Scotland',14,2,'Angus Gunn','player'),
('SCO3','SCO','Scotland',14,3,'Jack Hendry','player'),
('SCO4','SCO','Scotland',14,4,'Kieran Tierney','player'),
('SCO5','SCO','Scotland',14,5,'Aaron Hickey','player'),
('SCO6','SCO','Scotland',14,6,'Andrew Robertson','player'),
('SCO7','SCO','Scotland',14,7,'Scott McKenna','player'),
('SCO8','SCO','Scotland',14,8,'John Souttar','player'),
('SCO9','SCO','Scotland',14,9,'Anthony Ralston','player'),
('SCO10','SCO','Scotland',14,10,'Grant Hanley','player'),
('SCO11','SCO','Scotland',14,11,'Scott McTominay','player'),
('SCO12','SCO','Scotland',14,12,'Billy Gilmour','player'),
('SCO13','SCO','Scotland',14,13,'Team Photo','photo'),
('SCO14','SCO','Scotland',14,14,'Lewis Ferguson','player'),
('SCO15','SCO','Scotland',14,15,'Ryan Christie','player'),
('SCO16','SCO','Scotland',14,16,'Kenny McLean','player'),
('SCO17','SCO','Scotland',14,17,'John McGinn','player'),
('SCO18','SCO','Scotland',14,18,'Lyndon Dykes','player'),
('SCO19','SCO','Scotland',14,19,'Che Adams','player'),
('SCO20','SCO','Scotland',14,20,'Ben Gannon-Doak','player'),
('USA1','USA','USA',15,1,'Emblem','crest'),
('USA2','USA','USA',15,2,'Matt Freese','player'),
('USA3','USA','USA',15,3,'Chris Richards','player'),
('USA4','USA','USA',15,4,'Tim Ream','player'),
('USA5','USA','USA',15,5,'Mark McKenzie','player'),
('USA6','USA','USA',15,6,'Alex Freeman','player'),
('USA7','USA','USA',15,7,'Antonee Robinson','player'),
('USA8','USA','USA',15,8,'Tyler Adams','player'),
('USA9','USA','USA',15,9,'Tanner Tessmann','player'),
('USA10','USA','USA',15,10,'Weston McKenny','player'),
('USA11','USA','USA',15,11,'Christian Roldan','player'),
('USA12','USA','USA',15,12,'Timothy Weah','player'),
('USA13','USA','USA',15,13,'Team Photo','photo'),
('USA14','USA','USA',15,14,'Diego Luna','player'),
('USA15','USA','USA',15,15,'Malik Tillman','player'),
('USA16','USA','USA',15,16,'Christian Pulisic','player'),
('USA17','USA','USA',15,17,'Brenden Aaronson','player'),
('USA18','USA','USA',15,18,'Ricardo Pepi','player'),
('USA19','USA','USA',15,19,'Haji Wright','player'),
('USA20','USA','USA',15,20,'Folarin Balogun','player'),
('PAR1','PAR','Paraguay',16,1,'Emblem','crest'),
('PAR2','PAR','Paraguay',16,2,'Roberto Fernandez','player'),
('PAR3','PAR','Paraguay',16,3,'Orlando Gill','player'),
('PAR4','PAR','Paraguay',16,4,'Gustavo Gomez','player'),
('PAR5','PAR','Paraguay',16,5,'Fabián Balbuena','player'),
('PAR6','PAR','Paraguay',16,6,'Juan José Cáceres','player'),
('PAR7','PAR','Paraguay',16,7,'Omar Alderete','player'),
('PAR8','PAR','Paraguay',16,8,'Junior Alonso','player'),
('PAR9','PAR','Paraguay',16,9,'Mathías Villasanti','player'),
('PAR10','PAR','Paraguay',16,10,'Diego Gomez','player'),
('PAR11','PAR','Paraguay',16,11,'Damián Bobadilla','player'),
('PAR12','PAR','Paraguay',16,12,'Andres Cubas','player'),
('PAR13','PAR','Paraguay',16,13,'Team Photo','photo'),
('PAR14','PAR','Paraguay',16,14,'Matias Galarza Fonda','player'),
('PAR15','PAR','Paraguay',16,15,'Julio Enciso','player'),
('PAR16','PAR','Paraguay',16,16,'Alejandro Romero Gamarra','player'),
('PAR17','PAR','Paraguay',16,17,'Miguel Almirón','player'),
('PAR18','PAR','Paraguay',16,18,'Ramon Sosa','player'),
('PAR19','PAR','Paraguay',16,19,'Angel Romero','player'),
('PAR20','PAR','Paraguay',16,20,'Antonio Sanabria','player'),
('AUS1','AUS','Australia',17,1,'Emblem','crest'),
('AUS2','AUS','Australia',17,2,'Mathew Ryan','player'),
('AUS3','AUS','Australia',17,3,'Joe Gauci','player'),
('AUS4','AUS','Australia',17,4,'Harry Souttar','player'),
('AUS5','AUS','Australia',17,5,'Alessandro Circati','player'),
('AUS6','AUS','Australia',17,6,'Jordan Bos','player'),
('AUS7','AUS','Australia',17,7,'Aziz Behich','player'),
('AUS8','AUS','Australia',17,8,'Cameron Burgess','player'),
('AUS9','AUS','Australia',17,9,'Lewis Miller','player'),
('AUS10','AUS','Australia',17,10,'Milos Degenek','player'),
('AUS11','AUS','Australia',17,11,'Jackson Irvine','player'),
('AUS12','AUS','Australia',17,12,'Riley McGree','player'),
('AUS13','AUS','Australia',17,13,'Team Photo','photo'),
('AUS14','AUS','Australia',17,14,'Aiden O''Neill','player'),
('AUS15','AUS','Australia',17,15,'Connor Metcalfe','player'),
('AUS16','AUS','Australia',17,16,'Patrick Yazbek','player'),
('AUS17','AUS','Australia',17,17,'Craig Goodwin','player'),
('AUS18','AUS','Australia',17,18,'Kusini Yengi','player'),
('AUS19','AUS','Australia',17,19,'Nestory Irankunda','player'),
('AUS20','AUS','Australia',17,20,'Mohamed Touré','player'),
('TUR1','TUR','Türkiye',18,1,'Emblem','crest'),
('TUR2','TUR','Türkiye',18,2,'Ugurcan Cakir','player'),
('TUR3','TUR','Türkiye',18,3,'Mert Muldur','player'),
('TUR4','TUR','Türkiye',18,4,'Zeki Celik','player'),
('TUR5','TUR','Türkiye',18,5,'Abdulkerim Bardakci','player'),
('TUR6','TUR','Türkiye',18,6,'Caglar Soyuncu','player'),
('TUR7','TUR','Türkiye',18,7,'Merih Demiral','player'),
('TUR8','TUR','Türkiye',18,8,'Ferdi Kadioglu','player'),
('TUR9','TUR','Türkiye',18,9,'Kaan Ayhan','player'),
('TUR10','TUR','Türkiye',18,10,'Ismail Yuksek','player'),
('TUR11','TUR','Türkiye',18,11,'Hakan Calhanoglu','player'),
('TUR12','TUR','Türkiye',18,12,'Orkun Kokcu','player'),
('TUR13','TUR','Türkiye',18,13,'Team Photo','photo'),
('TUR14','TUR','Türkiye',18,14,'Arda Guler','player'),
('TUR15','TUR','Türkiye',18,15,'Irfan Can Kahveci','player'),
('TUR16','TUR','Türkiye',18,16,'Yunus Akgun','player'),
('TUR17','TUR','Türkiye',18,17,'Can Uzun','player'),
('TUR18','TUR','Türkiye',18,18,'Baris Alper Yilmaz','player'),
('TUR19','TUR','Türkiye',18,19,'Kerem Akturkoglu','player'),
('TUR20','TUR','Türkiye',18,20,'Kenan Yildiz','player'),
('GER1','GER','Germany',19,1,'Emblem','crest'),
('GER2','GER','Germany',19,2,'Marc-André ter Stegen','player'),
('GER3','GER','Germany',19,3,'Jonathan Tah','player'),
('GER4','GER','Germany',19,4,'David Raum','player'),
('GER5','GER','Germany',19,5,'Nico Schlotterbeck','player'),
('GER6','GER','Germany',19,6,'Antonio Rüdiger','player'),
('GER7','GER','Germany',19,7,'Waldemar Anton','player'),
('GER8','GER','Germany',19,8,'Ridle Baku','player'),
('GER9','GER','Germany',19,9,'Maximilian Mittelstadt','player'),
('GER10','GER','Germany',19,10,'Joshua Kimmich','player'),
('GER11','GER','Germany',19,11,'Florian Wirtz','player'),
('GER12','GER','Germany',19,12,'Felix Nmecha','player'),
('GER13','GER','Germany',19,13,'Team Photo','photo'),
('GER14','GER','Germany',19,14,'Leon Goretzka','player'),
('GER15','GER','Germany',19,15,'Jamal Musiala','player'),
('GER16','GER','Germany',19,16,'Serge Gnabry','player'),
('GER17','GER','Germany',19,17,'Kai Havertz','player'),
('GER18','GER','Germany',19,18,'Leroy Sane','player'),
('GER19','GER','Germany',19,19,'Karim Adeyemi','player'),
('GER20','GER','Germany',19,20,'Nick Woltemade','player'),
('CUW1','CUW','Curaçao',20,1,'Emblem','crest'),
('CUW2','CUW','Curaçao',20,2,'Eloy Room','player'),
('CUW3','CUW','Curaçao',20,3,'Armando Obispo','player'),
('CUW4','CUW','Curaçao',20,4,'Sherel Floranus','player'),
('CUW5','CUW','Curaçao',20,5,'Jurien Gaari','player'),
('CUW6','CUW','Curaçao',20,6,'Joshua Brenet','player'),
('CUW7','CUW','Curaçao',20,7,'Roshon Van Eijma','player'),
('CUW8','CUW','Curaçao',20,8,'Shurandy Sambo','player'),
('CUW9','CUW','Curaçao',20,9,'Livano Comenencia','player'),
('CUW10','CUW','Curaçao',20,10,'Godfried Roemeratoe','player'),
('CUW11','CUW','Curaçao',20,11,'Juninho Bacuna','player'),
('CUW12','CUW','Curaçao',20,12,'Leandro Bacuna','player'),
('CUW13','CUW','Curaçao',20,13,'Team Photo','photo'),
('CUW14','CUW','Curaçao',20,14,'Tahith Chong','player'),
('CUW15','CUW','Curaçao',20,15,'Kenji Gorre','player'),
('CUW16','CUW','Curaçao',20,16,'Jearl Margaritha','player'),
('CUW17','CUW','Curaçao',20,17,'Jurgen Locadia','player'),
('CUW18','CUW','Curaçao',20,18,'Jeremy Antonisse','player'),
('CUW19','CUW','Curaçao',20,19,'Gervane Kastaneer','player'),
('CUW20','CUW','Curaçao',20,20,'Sontje Hansen','player'),
('CIV1','CIV','Ivory Coast',21,1,'Emblem','crest'),
('CIV2','CIV','Ivory Coast',21,2,'Yahia Fofana','player'),
('CIV3','CIV','Ivory Coast',21,3,'Ghislain Konan','player'),
('CIV4','CIV','Ivory Coast',21,4,'Wilfried Singo','player'),
('CIV5','CIV','Ivory Coast',21,5,'Odilon Kossounou','player'),
('CIV6','CIV','Ivory Coast',21,6,'Evan Ndicka','player'),
('CIV7','CIV','Ivory Coast',21,7,'Willy Boly','player'),
('CIV8','CIV','Ivory Coast',21,8,'Emmanuel Agbadou','player'),
('CIV9','CIV','Ivory Coast',21,9,'Ousmane Diomande','player'),
('CIV10','CIV','Ivory Coast',21,10,'Franck Kessie','player'),
('CIV11','CIV','Ivory Coast',21,11,'Seko Fofana','player'),
('CIV12','CIV','Ivory Coast',21,12,'Ibrahim Sangare','player'),
('CIV13','CIV','Ivory Coast',21,13,'Team Photo','photo'),
('CIV14','CIV','Ivory Coast',21,14,'Jean-Philippe Gbamin','player'),
('CIV15','CIV','Ivory Coast',21,15,'Amad Diallo','player'),
('CIV16','CIV','Ivory Coast',21,16,'Sébastien Haller','player'),
('CIV17','CIV','Ivory Coast',21,17,'Simon Adingra','player'),
('CIV18','CIV','Ivory Coast',21,18,'Yan Diomande','player'),
('CIV19','CIV','Ivory Coast',21,19,'Evann Guessand','player'),
('CIV20','CIV','Ivory Coast',21,20,'Oumar Diakite','player'),
('ECU1','ECU','Ecuador',22,1,'Emblem','crest'),
('ECU2','ECU','Ecuador',22,2,'Hernán Galíndez','player'),
('ECU3','ECU','Ecuador',22,3,'Gonzalo Valle','player'),
('ECU4','ECU','Ecuador',22,4,'Piero Hincapié','player'),
('ECU5','ECU','Ecuador',22,5,'Pervis Estupiñán','player'),
('ECU6','ECU','Ecuador',22,6,'Willian Pacho','player'),
('ECU7','ECU','Ecuador',22,7,'Ángelo Preciado','player'),
('ECU8','ECU','Ecuador',22,8,'Joel Ordóñez','player'),
('ECU9','ECU','Ecuador',22,9,'Moises Caicedo','player'),
('ECU10','ECU','Ecuador',22,10,'Alan Franco','player'),
('ECU11','ECU','Ecuador',22,11,'Kendry Paez','player'),
('ECU12','ECU','Ecuador',22,12,'Pedro Vite','player'),
('ECU13','ECU','Ecuador',22,13,'Team Photo','photo'),
('ECU14','ECU','Ecuador',22,14,'John Yeboah','player'),
('ECU15','ECU','Ecuador',22,15,'Leonardo Campana','player'),
('ECU16','ECU','Ecuador',22,16,'Gonzalo Plata','player'),
('ECU17','ECU','Ecuador',22,17,'Nilson Angulo','player'),
('ECU18','ECU','Ecuador',22,18,'Alan Minda','player'),
('ECU19','ECU','Ecuador',22,19,'Kevin Rodriguez','player'),
('ECU20','ECU','Ecuador',22,20,'Enner Valencia','player'),
('NED1','NED','Netherlands',23,1,'Emblem','crest'),
('NED2','NED','Netherlands',23,2,'Bart Verbruggen','player'),
('NED3','NED','Netherlands',23,3,'Virgil van Dijk','player'),
('NED4','NED','Netherlands',23,4,'Micky van de Ven','player'),
('NED5','NED','Netherlands',23,5,'Jurrien Timber','player'),
('NED6','NED','Netherlands',23,6,'Denzel Dumfries','player'),
('NED7','NED','Netherlands',23,7,'Nathan Aké','player'),
('NED8','NED','Netherlands',23,8,'Jeremie Frimpong','player'),
('NED9','NED','Netherlands',23,9,'Jan Paul van Hecke','player'),
('NED10','NED','Netherlands',23,10,'Tijjani Reijnders','player'),
('NED11','NED','Netherlands',23,11,'Ryan Gravenberch','player'),
('NED12','NED','Netherlands',23,12,'Teun Koopmeiners','player'),
('NED13','NED','Netherlands',23,13,'Team Photo','photo'),
('NED14','NED','Netherlands',23,14,'Frenkie de Jong','player'),
('NED15','NED','Netherlands',23,15,'Xavi Simons','player'),
('NED16','NED','Netherlands',23,16,'Justin Kluivert','player'),
('NED17','NED','Netherlands',23,17,'Memphis Depay','player'),
('NED18','NED','Netherlands',23,18,'Donyell Malen','player'),
('NED19','NED','Netherlands',23,19,'Wout Weghorst','player'),
('NED20','NED','Netherlands',23,20,'Cody Gakpo','player'),
('JPN1','JPN','Japan',24,1,'Emblem','crest'),
('JPN2','JPN','Japan',24,2,'Zion Suzuki','player'),
('JPN3','JPN','Japan',24,3,'Henry Heroki Mochizuki','player'),
('JPN4','JPN','Japan',24,4,'Ayumu Seko','player'),
('JPN5','JPN','Japan',24,5,'Junnosuke Suzuki','player'),
('JPN6','JPN','Japan',24,6,'Shogo Taniguchi','player'),
('JPN7','JPN','Japan',24,7,'Tsuyoshi Watanabe','player'),
('JPN8','JPN','Japan',24,8,'Kaishu Sano','player'),
('JPN9','JPN','Japan',24,9,'Yuki Soma','player'),
('JPN10','JPN','Japan',24,10,'Ao Tanaka','player'),
('JPN11','JPN','Japan',24,11,'Daichi Kamada','player'),
('JPN12','JPN','Japan',24,12,'Takefusa Kubo','player'),
('JPN13','JPN','Japan',24,13,'Team Photo','photo'),
('JPN14','JPN','Japan',24,14,'Ritsu Doan','player'),
('JPN15','JPN','Japan',24,15,'Keito Nakamura','player'),
('JPN16','JPN','Japan',24,16,'Takumi Minamino','player'),
('JPN17','JPN','Japan',24,17,'Shuto Machino','player'),
('JPN18','JPN','Japan',24,18,'Junya Ito','player'),
('JPN19','JPN','Japan',24,19,'Koki Ogawa','player'),
('JPN20','JPN','Japan',24,20,'Ayase Ueda','player'),
('SWE1','SWE','Sweden',25,1,'Emblem','crest'),
('SWE2','SWE','Sweden',25,2,'Victor Johansson','player'),
('SWE3','SWE','Sweden',25,3,'Isak Hien','player'),
('SWE4','SWE','Sweden',25,4,'Gabriel Gudmundsson','player'),
('SWE5','SWE','Sweden',25,5,'Emil Holm','player'),
('SWE6','SWE','Sweden',25,6,'Victor Nilsson Lindelöf','player'),
('SWE7','SWE','Sweden',25,7,'Gustaf Lagerbielke','player'),
('SWE8','SWE','Sweden',25,8,'Lucas Bergvall','player'),
('SWE9','SWE','Sweden',25,9,'Hugo Larsson','player'),
('SWE10','SWE','Sweden',25,10,'Jesper Karlström','player'),
('SWE11','SWE','Sweden',25,11,'Yasin Ayari','player'),
('SWE12','SWE','Sweden',25,12,'Mattias Svanberg','player'),
('SWE13','SWE','Sweden',25,13,'Team Photo','photo'),
('SWE14','SWE','Sweden',25,14,'Daniel Svensson','player'),
('SWE15','SWE','Sweden',25,15,'Ken Sema','player'),
('SWE16','SWE','Sweden',25,16,'Roony Bardghji','player'),
('SWE17','SWE','Sweden',25,17,'Dejan Kulusevski','player'),
('SWE18','SWE','Sweden',25,18,'Anthony Elanga','player'),
('SWE19','SWE','Sweden',25,19,'Alexander Isak','player'),
('SWE20','SWE','Sweden',25,20,'Viktor Gyökeres','player'),
('TUN1','TUN','Tunisia',26,1,'Emblem','crest'),
('TUN2','TUN','Tunisia',26,2,'Bechir Ben Said','player'),
('TUN3','TUN','Tunisia',26,3,'Aymen Dahmen','player'),
('TUN4','TUN','Tunisia',26,4,'Yan Valery','player'),
('TUN5','TUN','Tunisia',26,5,'Montassar Talbi','player'),
('TUN6','TUN','Tunisia',26,6,'Yassine Meriah','player'),
('TUN7','TUN','Tunisia',26,7,'Ali Abdi','player'),
('TUN8','TUN','Tunisia',26,8,'Dylan Bronn','player'),
('TUN9','TUN','Tunisia',26,9,'Ellyes Skhiri','player'),
('TUN10','TUN','Tunisia',26,10,'Aissa Laidouni','player'),
('TUN11','TUN','Tunisia',26,11,'Ferjani Sassi','player'),
('TUN12','TUN','Tunisia',26,12,'Mohamed Ali Ben Romdhane','player'),
('TUN13','TUN','Tunisia',26,13,'Team Photo','photo'),
('TUN14','TUN','Tunisia',26,14,'Hannibal Mejbri','player'),
('TUN15','TUN','Tunisia',26,15,'Elias Achouri','player'),
('TUN16','TUN','Tunisia',26,16,'Elias Saad','player'),
('TUN17','TUN','Tunisia',26,17,'Hazem Mastouri','player'),
('TUN18','TUN','Tunisia',26,18,'Ismael Gharbi','player'),
('TUN19','TUN','Tunisia',26,19,'Sayfallah Ltaief','player'),
('TUN20','TUN','Tunisia',26,20,'Naim Sliti','player'),
('BEL1','BEL','Belgium',27,1,'Emblem','crest'),
('BEL2','BEL','Belgium',27,2,'Thibaut Courtois','player'),
('BEL3','BEL','Belgium',27,3,'Arthur Theate','player'),
('BEL4','BEL','Belgium',27,4,'Timothy Castagne','player'),
('BEL5','BEL','Belgium',27,5,'Zeno Debast','player'),
('BEL6','BEL','Belgium',27,6,'Brandon Mechele','player'),
('BEL7','BEL','Belgium',27,7,'Maxim De Cuyper','player'),
('BEL8','BEL','Belgium',27,8,'Thomas Meunier','player'),
('BEL9','BEL','Belgium',27,9,'Youri Tielemans','player'),
('BEL10','BEL','Belgium',27,10,'Amadou Onana','player'),
('BEL11','BEL','Belgium',27,11,'Nicolas Raskin','player'),
('BEL12','BEL','Belgium',27,12,'Alexis Saelemaekers','player'),
('BEL13','BEL','Belgium',27,13,'Team Photo','photo'),
('BEL14','BEL','Belgium',27,14,'Hans Vanaken','player'),
('BEL15','BEL','Belgium',27,15,'Kevin De Bruyne','player'),
('BEL16','BEL','Belgium',27,16,'Jérémy Doku','player'),
('BEL17','BEL','Belgium',27,17,'Charles De Ketelaere','player'),
('BEL18','BEL','Belgium',27,18,'Leandro Trossard','player'),
('BEL19','BEL','Belgium',27,19,'Loïs Openda','player'),
('BEL20','BEL','Belgium',27,20,'Romelu Lukaku','player'),
('EGY1','EGY','Egypt',28,1,'Emblem','crest'),
('EGY2','EGY','Egypt',28,2,'Mohamed El Shenawy','player'),
('EGY3','EGY','Egypt',28,3,'Mohamed Hany','player'),
('EGY4','EGY','Egypt',28,4,'Mohamed Hamdy','player'),
('EGY5','EGY','Egypt',28,5,'Yasser Ibrahim','player'),
('EGY6','EGY','Egypt',28,6,'Khaled Sobhi','player'),
('EGY7','EGY','Egypt',28,7,'Ramy Rabia','player'),
('EGY8','EGY','Egypt',28,8,'Hossam Abdelmaguid','player'),
('EGY9','EGY','Egypt',28,9,'Ahmed Fatouh','player'),
('EGY10','EGY','Egypt',28,10,'Marwan Attia','player'),
('EGY11','EGY','Egypt',28,11,'Zizo','player'),
('EGY12','EGY','Egypt',28,12,'Hamdy Fathy','player'),
('EGY13','EGY','Egypt',28,13,'Team Photo','photo'),
('EGY14','EGY','Egypt',28,14,'Mohamed Lasheen','player'),
('EGY15','EGY','Egypt',28,15,'Emam Ashour','player'),
('EGY16','EGY','Egypt',28,16,'Osama Faisal','player'),
('EGY17','EGY','Egypt',28,17,'Mohamed Salah','player'),
('EGY18','EGY','Egypt',28,18,'Mostafa Mohamed','player'),
('EGY19','EGY','Egypt',28,19,'Trezeguet','player'),
('EGY20','EGY','Egypt',28,20,'Omar Marmoush','player'),
('IRN1','IRN','Iran',29,1,'Emblem','crest'),
('IRN2','IRN','Iran',29,2,'Alireza Beiranvand','player'),
('IRN3','IRN','Iran',29,3,'Morteza Pouraliganji','player'),
('IRN4','IRN','Iran',29,4,'Ehsan Hajsafi','player'),
('IRN5','IRN','Iran',29,5,'Milad Mohammadi','player'),
('IRN6','IRN','Iran',29,6,'Shojae Khalilzadeh','player'),
('IRN7','IRN','Iran',29,7,'Ramin Rezaeian','player'),
('IRN8','IRN','Iran',29,8,'Hossein Kanaani','player'),
('IRN9','IRN','Iran',29,9,'Sadegh Moharrami','player'),
('IRN10','IRN','Iran',29,10,'Saleh Hardani','player'),
('IRN11','IRN','Iran',29,11,'Saeed Ezatolahi','player'),
('IRN12','IRN','Iran',29,12,'Saman Ghoddos','player'),
('IRN13','IRN','Iran',29,13,'Team Photo','photo'),
('IRN14','IRN','Iran',29,14,'Omid Noorafkan','player'),
('IRN15','IRN','Iran',29,15,'Roozbeh Cheshmi','player'),
('IRN16','IRN','Iran',29,16,'Mohammad Mohebi','player'),
('IRN17','IRN','Iran',29,17,'Sardar Azmoun','player'),
('IRN18','IRN','Iran',29,18,'Mehdi Taremi','player'),
('IRN19','IRN','Iran',29,19,'Alireza Jahanbakhsh','player'),
('IRN20','IRN','Iran',29,20,'Ali Gholizadeh','player'),
('NZL1','NZL','New Zealand',30,1,'Emblem','crest'),
('NZL2','NZL','New Zealand',30,2,'Max Crocombe','player'),
('NZL3','NZL','New Zealand',30,3,'Alex Paulsen','player'),
('NZL4','NZL','New Zealand',30,4,'Michael Boxall','player'),
('NZL5','NZL','New Zealand',30,5,'Liberato Cacace','player'),
('NZL6','NZL','New Zealand',30,6,'Tim Payne','player'),
('NZL7','NZL','New Zealand',30,7,'Tyler Bindon','player'),
('NZL8','NZL','New Zealand',30,8,'Francis de Vries','player'),
('NZL9','NZL','New Zealand',30,9,'Finn Surman','player'),
('NZL10','NZL','New Zealand',30,10,'Joe Bell','player'),
('NZL11','NZL','New Zealand',30,11,'Sarpreet Singh','player'),
('NZL12','NZL','New Zealand',30,12,'Ryan Thomas','player'),
('NZL13','NZL','New Zealand',30,13,'Team Photo','photo'),
('NZL14','NZL','New Zealand',30,14,'Matthew Garbett','player'),
('NZL15','NZL','New Zealand',30,15,'Marko Stamenić','player'),
('NZL16','NZL','New Zealand',30,16,'Ben Old','player'),
('NZL17','NZL','New Zealand',30,17,'Chris Wood','player'),
('NZL18','NZL','New Zealand',30,18,'Elijah Just','player'),
('NZL19','NZL','New Zealand',30,19,'Callum McCowatt','player'),
('NZL20','NZL','New Zealand',30,20,'Kosta Barbarouses','player'),
('ESP1','ESP','Spain',31,1,'Emblem','crest'),
('ESP2','ESP','Spain',31,2,'Unai Simon','player'),
('ESP3','ESP','Spain',31,3,'Robin Le Normand','player'),
('ESP4','ESP','Spain',31,4,'Aymeric Laporte','player'),
('ESP5','ESP','Spain',31,5,'Dean Huijsen','player'),
('ESP6','ESP','Spain',31,6,'Pedro Porro','player'),
('ESP7','ESP','Spain',31,7,'Dani Carvajal','player'),
('ESP8','ESP','Spain',31,8,'Marc Cucurella','player'),
('ESP9','ESP','Spain',31,9,'Martín Zubimendi','player'),
('ESP10','ESP','Spain',31,10,'Rodri','player'),
('ESP11','ESP','Spain',31,11,'Pedri','player'),
('ESP12','ESP','Spain',31,12,'Fabian Ruiz','player'),
('ESP13','ESP','Spain',31,13,'Team Photo','photo'),
('ESP14','ESP','Spain',31,14,'Mikel Merino','player'),
('ESP15','ESP','Spain',31,15,'Lamine Yamal','player'),
('ESP16','ESP','Spain',31,16,'Dani Olmo','player'),
('ESP17','ESP','Spain',31,17,'Nico Williams','player'),
('ESP18','ESP','Spain',31,18,'Ferran Torres','player'),
('ESP19','ESP','Spain',31,19,'Álvaro Morata','player'),
('ESP20','ESP','Spain',31,20,'Mikel Oyarzabal','player'),
('CPV1','CPV','Cape Verde',32,1,'Emblem','crest'),
('CPV2','CPV','Cape Verde',32,2,'Vozinha','player'),
('CPV3','CPV','Cape Verde',32,3,'Logan Costa','player'),
('CPV4','CPV','Cape Verde',32,4,'Pico','player'),
('CPV5','CPV','Cape Verde',32,5,'Diney','player'),
('CPV6','CPV','Cape Verde',32,6,'Steven Moreira','player'),
('CPV7','CPV','Cape Verde',32,7,'Wagner Pina','player'),
('CPV8','CPV','Cape Verde',32,8,'Joao Paulo','player'),
('CPV9','CPV','Cape Verde',32,9,'Yannick Semedo','player'),
('CPV10','CPV','Cape Verde',32,10,'Kevin Pina','player'),
('CPV11','CPV','Cape Verde',32,11,'Patrick Andrade','player'),
('CPV12','CPV','Cape Verde',32,12,'Jamiro Monteiro','player'),
('CPV13','CPV','Cape Verde',32,13,'Team Photo','photo'),
('CPV14','CPV','Cape Verde',32,14,'Deroy Duarte','player'),
('CPV15','CPV','Cape Verde',32,15,'Garry Rodrigues','player'),
('CPV16','CPV','Cape Verde',32,16,'Jovane Cabral','player'),
('CPV17','CPV','Cape Verde',32,17,'Ryan Mendes','player'),
('CPV18','CPV','Cape Verde',32,18,'Dailon Livramento','player'),
('CPV19','CPV','Cape Verde',32,19,'Willy Semedo','player'),
('CPV20','CPV','Cape Verde',32,20,'Bebe','player'),
('KSA1','KSA','Saudi Arabia',33,1,'Emblem','crest'),
('KSA2','KSA','Saudi Arabia',33,2,'Nawaf Alaqidi','player'),
('KSA3','KSA','Saudi Arabia',33,3,'Abdulrahman Al-Sanbi','player'),
('KSA4','KSA','Saudi Arabia',33,4,'Saud Abdulhamid','player'),
('KSA5','KSA','Saudi Arabia',33,5,'Nawaf Bouwashl','player'),
('KSA6','KSA','Saudi Arabia',33,6,'Jihad Thakri','player'),
('KSA7','KSA','Saudi Arabia',33,7,'Moteb Al-Harbi','player'),
('KSA8','KSA','Saudi Arabia',33,8,'Hassan Altambakti','player'),
('KSA9','KSA','Saudi Arabia',33,9,'Musab Aljuwayr','player'),
('KSA10','KSA','Saudi Arabia',33,10,'Ziyad Aljohani','player'),
('KSA11','KSA','Saudi Arabia',33,11,'Abdullah Alkhaibari','player'),
('KSA12','KSA','Saudi Arabia',33,12,'Nasser Aldawsari','player'),
('KSA13','KSA','Saudi Arabia',33,13,'Team Photo','photo'),
('KSA14','KSA','Saudi Arabia',33,14,'Saleh Abu Alshamat','player'),
('KSA15','KSA','Saudi Arabia',33,15,'Marwan Alsahafi','player'),
('KSA16','KSA','Saudi Arabia',33,16,'Salem Aldawsari','player'),
('KSA17','KSA','Saudi Arabia',33,17,'Abdulrahman Al-Aboud','player'),
('KSA18','KSA','Saudi Arabia',33,18,'Feras Akbrikan','player'),
('KSA19','KSA','Saudi Arabia',33,19,'Saleh Alshehri','player'),
('KSA20','KSA','Saudi Arabia',33,20,'Abdullah Al-Hamdan','player'),
('URU1','URU','Uruguay',34,1,'Emblem','crest'),
('URU2','URU','Uruguay',34,2,'Sergio Rochet','player'),
('URU3','URU','Uruguay',34,3,'Santiago Mele','player'),
('URU4','URU','Uruguay',34,4,'Ronald Araujo','player'),
('URU5','URU','Uruguay',34,5,'José María Giménez','player'),
('URU6','URU','Uruguay',34,6,'Sebastian Caceres','player'),
('URU7','URU','Uruguay',34,7,'Mathias Olivera','player'),
('URU8','URU','Uruguay',34,8,'Guillermo Varela','player'),
('URU9','URU','Uruguay',34,9,'Nahitan Nandez','player'),
('URU10','URU','Uruguay',34,10,'Federico Valverde','player'),
('URU11','URU','Uruguay',34,11,'Giorgian De Arrascaeta','player'),
('URU12','URU','Uruguay',34,12,'Rodrigo Bentancur','player'),
('URU13','URU','Uruguay',34,13,'Team Photo','photo'),
('URU14','URU','Uruguay',34,14,'Manuel Ugarte','player'),
('URU15','URU','Uruguay',34,15,'Nicolás de la Cruz','player'),
('URU16','URU','Uruguay',34,16,'Maxi Araujo','player'),
('URU17','URU','Uruguay',34,17,'Darwin Núñez','player'),
('URU18','URU','Uruguay',34,18,'Federico Viñas','player'),
('URU19','URU','Uruguay',34,19,'Rodrigo Aguirre','player'),
('URU20','URU','Uruguay',34,20,'Facundo Pellistri','player'),
('FRA1','FRA','France',35,1,'Emblem','crest'),
('FRA2','FRA','France',35,2,'Mike Maignan','player'),
('FRA3','FRA','France',35,3,'Theo Hernandez','player'),
('FRA4','FRA','France',35,4,'William Saliba','player'),
('FRA5','FRA','France',35,5,'Jules Kounde','player'),
('FRA6','FRA','France',35,6,'Ibrahima Konate','player'),
('FRA7','FRA','France',35,7,'Dayot Upamecano','player'),
('FRA8','FRA','France',35,8,'Lucas Digne','player'),
('FRA9','FRA','France',35,9,'Aurélien Tchouaméni','player'),
('FRA10','FRA','France',35,10,'Eduardo Camavinga','player'),
('FRA11','FRA','France',35,11,'Manu Kone','player'),
('FRA12','FRA','France',35,12,'Adrien Rabiot','player'),
('FRA13','FRA','France',35,13,'Team Photo','photo'),
('FRA14','FRA','France',35,14,'Michael Olise','player'),
('FRA15','FRA','France',35,15,'Ousmane Dembele','player'),
('FRA16','FRA','France',35,16,'Bradley Barcola','player'),
('FRA17','FRA','France',35,17,'Désiré Doué','player'),
('FRA18','FRA','France',35,18,'Kingsley Coman','player'),
('FRA19','FRA','France',35,19,'Hugo Ekitike','player'),
('FRA20','FRA','France',35,20,'Kylian Mbappe','player'),
('SEN1','SEN','Senegal',36,1,'Emblem','crest'),
('SEN2','SEN','Senegal',36,2,'Édouard Mendy','player'),
('SEN3','SEN','Senegal',36,3,'Yehvann Diouf','player'),
('SEN4','SEN','Senegal',36,4,'Moussa Niakhaté','player'),
('SEN5','SEN','Senegal',36,5,'Abdoulaye Seck','player'),
('SEN6','SEN','Senegal',36,6,'Ismail Jakobs','player'),
('SEN7','SEN','Senegal',36,7,'El Hadji Malick Diouf','player'),
('SEN8','SEN','Senegal',36,8,'Kalidou Koulibaly','player'),
('SEN9','SEN','Senegal',36,9,'Idrissa Gana Gueye','player'),
('SEN10','SEN','Senegal',36,10,'Pape Matar Sarr','player'),
('SEN11','SEN','Senegal',36,11,'Pape Gueye','player'),
('SEN12','SEN','Senegal',36,12,'Habib Diarra','player'),
('SEN13','SEN','Senegal',36,13,'Team Photo','photo'),
('SEN14','SEN','Senegal',36,14,'Lamine Camara','player'),
('SEN15','SEN','Senegal',36,15,'Sadio Mane','player'),
('SEN16','SEN','Senegal',36,16,'Ismaïla Sarr','player'),
('SEN17','SEN','Senegal',36,17,'Boulaye Dia','player'),
('SEN18','SEN','Senegal',36,18,'Iliman Ndiaye','player'),
('SEN19','SEN','Senegal',36,19,'Nicolas Jackson','player'),
('SEN20','SEN','Senegal',36,20,'Krepin Diatta','player'),
('IRQ1','IRQ','Iraq',37,1,'Emblem','crest'),
('IRQ2','IRQ','Iraq',37,2,'Jalal Hassan','player'),
('IRQ3','IRQ','Iraq',37,3,'Rebin Sulaka','player'),
('IRQ4','IRQ','Iraq',37,4,'Hussein Ali','player'),
('IRQ5','IRQ','Iraq',37,5,'Akam Hashem','player'),
('IRQ6','IRQ','Iraq',37,6,'Merchas Doski','player'),
('IRQ7','IRQ','Iraq',37,7,'Zaid Tahseen','player'),
('IRQ8','IRQ','Iraq',37,8,'Manaf Younis','player'),
('IRQ9','IRQ','Iraq',37,9,'Zidane Iqbal','player'),
('IRQ10','IRQ','Iraq',37,10,'Amir Al-Ammari','player'),
('IRQ11','IRQ','Iraq',37,11,'Ibrahim Bavesh','player'),
('IRQ12','IRQ','Iraq',37,12,'Ali Jasim','player'),
('IRQ13','IRQ','Iraq',37,13,'Team Photo','photo'),
('IRQ14','IRQ','Iraq',37,14,'Youssef Amyn','player'),
('IRQ15','IRQ','Iraq',37,15,'Aimar Sher','player'),
('IRQ16','IRQ','Iraq',37,16,'Marko Farji','player'),
('IRQ17','IRQ','Iraq',37,17,'Osama Rashid','player'),
('IRQ18','IRQ','Iraq',37,18,'Ali Al-Hamadi','player'),
('IRQ19','IRQ','Iraq',37,19,'Aymen Hussein','player'),
('IRQ20','IRQ','Iraq',37,20,'Mohanad Ali','player'),
('NOR1','NOR','Norway',38,1,'Emblem','crest'),
('NOR2','NOR','Norway',38,2,'Orjan Nyland','player'),
('NOR3','NOR','Norway',38,3,'Julian Ryerson','player'),
('NOR4','NOR','Norway',38,4,'Leo Ostigård','player'),
('NOR5','NOR','Norway',38,5,'Kristoffer Vassbakk Ajer','player'),
('NOR6','NOR','Norway',38,6,'Marcus Holmgren Pedersen','player'),
('NOR7','NOR','Norway',38,7,'David Møller Wolfe','player'),
('NOR8','NOR','Norway',38,8,'Torbjørn Heggem','player'),
('NOR9','NOR','Norway',38,9,'Morten Thorsby','player'),
('NOR10','NOR','Norway',38,10,'Martin Ødegaard','player'),
('NOR11','NOR','Norway',38,11,'Sander Berge','player'),
('NOR12','NOR','Norway',38,12,'Andreas Schjelderup','player'),
('NOR13','NOR','Norway',38,13,'Team Photo','photo'),
('NOR14','NOR','Norway',38,14,'Patrick Berg','player'),
('NOR15','NOR','Norway',38,15,'Erling Haaland','player'),
('NOR16','NOR','Norway',38,16,'Alexander Sørloth','player'),
('NOR17','NOR','Norway',38,17,'Aron Dønnum','player'),
('NOR18','NOR','Norway',38,18,'Jorgen Strand Larsen','player'),
('NOR19','NOR','Norway',38,19,'Antonio Nusa','player'),
('NOR20','NOR','Norway',38,20,'Oscar Bobb','player'),
('ARG1','ARG','Argentina',39,1,'Emblem','crest'),
('ARG2','ARG','Argentina',39,2,'Emiliano Martinez','player'),
('ARG3','ARG','Argentina',39,3,'Nahuel Molina','player'),
('ARG4','ARG','Argentina',39,4,'Cristian Romero','player'),
('ARG5','ARG','Argentina',39,5,'Nicolas Otamendi','player'),
('ARG6','ARG','Argentina',39,6,'Nicolas Tagliafico','player'),
('ARG7','ARG','Argentina',39,7,'Leonardo Balerdi','player'),
('ARG8','ARG','Argentina',39,8,'Enzo Fernandez','player'),
('ARG9','ARG','Argentina',39,9,'Alexis Mac Allister','player'),
('ARG10','ARG','Argentina',39,10,'Rodrigo De Paul','player'),
('ARG11','ARG','Argentina',39,11,'Exequiel Palacios','player'),
('ARG12','ARG','Argentina',39,12,'Leandro Paredes','player'),
('ARG13','ARG','Argentina',39,13,'Team Photo','photo'),
('ARG14','ARG','Argentina',39,14,'Nico Paz','player'),
('ARG15','ARG','Argentina',39,15,'Franco Mastantuono','player'),
('ARG16','ARG','Argentina',39,16,'Nico Gonzalez','player'),
('ARG17','ARG','Argentina',39,17,'Lionel Messi','player'),
('ARG18','ARG','Argentina',39,18,'Lautaro Martinez','player'),
('ARG19','ARG','Argentina',39,19,'Julian Alvarez','player'),
('ARG20','ARG','Argentina',39,20,'Giuliano Simeone','player'),
('ALG1','ALG','Algeria',40,1,'Emblem','crest'),
('ALG2','ALG','Algeria',40,2,'Alexis Guendouz','player'),
('ALG3','ALG','Algeria',40,3,'Ramy Bensebaini','player'),
('ALG4','ALG','Algeria',40,4,'Youcef Atal','player'),
('ALG5','ALG','Algeria',40,5,'Rayan Aït-Nouri','player'),
('ALG6','ALG','Algeria',40,6,'Mohamed Amine Tougai','player'),
('ALG7','ALG','Algeria',40,7,'Aïssa Mandi','player'),
('ALG8','ALG','Algeria',40,8,'Ismael Bennacer','player'),
('ALG9','ALG','Algeria',40,9,'Houssem Aouar','player'),
('ALG10','ALG','Algeria',40,10,'Hicham Boudaoui','player'),
('ALG11','ALG','Algeria',40,11,'Ramiz Zerrouki','player'),
('ALG12','ALG','Algeria',40,12,'Nabil Bentaleb','player'),
('ALG13','ALG','Algeria',40,13,'Team Photo','photo'),
('ALG14','ALG','Algeria',40,14,'Farés Chaibi','player'),
('ALG15','ALG','Algeria',40,15,'Riyad Mahrez','player'),
('ALG16','ALG','Algeria',40,16,'Said Benrahma','player'),
('ALG17','ALG','Algeria',40,17,'Anis Hadj Moussa','player'),
('ALG18','ALG','Algeria',40,18,'Amine Gouiri','player'),
('ALG19','ALG','Algeria',40,19,'Baghdad Bounedjah','player'),
('ALG20','ALG','Algeria',40,20,'Mohammed Amoura','player'),
('AUT1','AUT','Austria',41,1,'Emblem','crest'),
('AUT2','AUT','Austria',41,2,'Alexander Schlager','player'),
('AUT3','AUT','Austria',41,3,'Patrick Pentz','player'),
('AUT4','AUT','Austria',41,4,'David Alaba','player'),
('AUT5','AUT','Austria',41,5,'Kevin Danso','player'),
('AUT6','AUT','Austria',41,6,'Philipp Lienhart','player'),
('AUT7','AUT','Austria',41,7,'Stefan Posch','player'),
('AUT8','AUT','Austria',41,8,'Phillipp Mwene','player'),
('AUT9','AUT','Austria',41,9,'Alexander Prass','player'),
('AUT10','AUT','Austria',41,10,'Xaver Schlager','player'),
('AUT11','AUT','Austria',41,11,'Marcel Sabitzer','player'),
('AUT12','AUT','Austria',41,12,'Konrad Laimer','player'),
('AUT13','AUT','Austria',41,13,'Team Photo','photo'),
('AUT14','AUT','Austria',41,14,'Florian Grillitsch','player'),
('AUT15','AUT','Austria',41,15,'Nicolas Seiwald','player'),
('AUT16','AUT','Austria',41,16,'Romano Schmid','player'),
('AUT17','AUT','Austria',41,17,'Patrick Wimmer','player'),
('AUT18','AUT','Austria',41,18,'Christoph Baumgartner','player'),
('AUT19','AUT','Austria',41,19,'Michael Gregoritsch','player'),
('AUT20','AUT','Austria',41,20,'Marko Arnautović','player'),
('JOR1','JOR','Jordan',42,1,'Emblem','crest'),
('JOR2','JOR','Jordan',42,2,'Yazeed Abulaila','player'),
('JOR3','JOR','Jordan',42,3,'Ihsan Haddad','player'),
('JOR4','JOR','Jordan',42,4,'Mohammad Abu Hashish','player'),
('JOR5','JOR','Jordan',42,5,'Yazan Al-Arab','player'),
('JOR6','JOR','Jordan',42,6,'Abdallah Nasib','player'),
('JOR7','JOR','Jordan',42,7,'Saleem Obaid','player'),
('JOR8','JOR','Jordan',42,8,'Mohammad Abualnadi','player'),
('JOR9','JOR','Jordan',42,9,'Ibrahim Saadeh','player'),
('JOR10','JOR','Jordan',42,10,'Nizar Al-Rashdan','player'),
('JOR11','JOR','Jordan',42,11,'Noor Al-Rawabdeh','player'),
('JOR12','JOR','Jordan',42,12,'Mohannad Abu Taha','player'),
('JOR13','JOR','Jordan',42,13,'Team Photo','photo'),
('JOR14','JOR','Jordan',42,14,'Amer Jamous','player'),
('JOR15','JOR','Jordan',42,15,'Musa Al-Taamari','player'),
('JOR16','JOR','Jordan',42,16,'Yazan Al-Naimat','player'),
('JOR17','JOR','Jordan',42,17,'Mahmoud Al-Mardi','player'),
('JOR18','JOR','Jordan',42,18,'Ali Olwan','player'),
('JOR19','JOR','Jordan',42,19,'Mohammad Abu Zrayq','player'),
('JOR20','JOR','Jordan',42,20,'Ibrahim Sabra','player'),
('POR1','POR','Portugal',43,1,'Emblem','crest'),
('POR2','POR','Portugal',43,2,'Diogo Costa','player'),
('POR3','POR','Portugal',43,3,'José Sá','player'),
('POR4','POR','Portugal',43,4,'Ruben Dias','player'),
('POR5','POR','Portugal',43,5,'João Cancelo','player'),
('POR6','POR','Portugal',43,6,'Diogo Dalot','player'),
('POR7','POR','Portugal',43,7,'Nuno Mendes','player'),
('POR8','POR','Portugal',43,8,'Gonçalo Inácio','player'),
('POR9','POR','Portugal',43,9,'Bernardo Silva','player'),
('POR10','POR','Portugal',43,10,'Bruno Fernandes','player'),
('POR11','POR','Portugal',43,11,'Ruben Neves','player'),
('POR12','POR','Portugal',43,12,'Vitinha','player'),
('POR13','POR','Portugal',43,13,'Team Photo','photo'),
('POR14','POR','Portugal',43,14,'João Neves','player'),
('POR15','POR','Portugal',43,15,'Cristiano Ronaldo','player'),
('POR16','POR','Portugal',43,16,'Francisco Trincao','player'),
('POR17','POR','Portugal',43,17,'João Felix','player'),
('POR18','POR','Portugal',43,18,'Gonçalo Ramos','player'),
('POR19','POR','Portugal',43,19,'Pedro Neto','player'),
('POR20','POR','Portugal',43,20,'Rafael Leão','player'),
('COD1','COD','Congo DR',44,1,'Emblem','crest'),
('COD2','COD','Congo DR',44,2,'Lionel Mpasi-Nzau','player'),
('COD3','COD','Congo DR',44,3,'Aaron Wan-Bissaka','player'),
('COD4','COD','Congo DR',44,4,'Axel Tuanzebe','player'),
('COD5','COD','Congo DR',44,5,'Arthur Masuaku','player'),
('COD6','COD','Congo DR',44,6,'Chancel Mbemba','player'),
('COD7','COD','Congo DR',44,7,'Joris Kayembe','player'),
('COD8','COD','Congo DR',44,8,'Charles Pickel','player'),
('COD9','COD','Congo DR',44,9,'Ngal''ayel Mukau','player'),
('COD10','COD','Congo DR',44,10,'Edo Kayembe','player'),
('COD11','COD','Congo DR',44,11,'Samuel Moutoussamy','player'),
('COD12','COD','Congo DR',44,12,'Noah Sadiki','player'),
('COD13','COD','Congo DR',44,13,'Team Photo','photo'),
('COD14','COD','Congo DR',44,14,'Théo Bongonda','player'),
('COD15','COD','Congo DR',44,15,'Meschak Elia','player'),
('COD16','COD','Congo DR',44,16,'Yoane Wissa','player'),
('COD17','COD','Congo DR',44,17,'Brian Cipenga','player'),
('COD18','COD','Congo DR',44,18,'Fiston Mayele','player'),
('COD19','COD','Congo DR',44,19,'Cédric Bakambu','player'),
('COD20','COD','Congo DR',44,20,'Nathanaël Mbuku','player'),
('UZB1','UZB','Uzbekistan',45,1,'Emblem','crest'),
('UZB2','UZB','Uzbekistan',45,2,'Utkir Yusupov','player'),
('UZB3','UZB','Uzbekistan',45,3,'Farrukh Savfiev','player'),
('UZB4','UZB','Uzbekistan',45,4,'Sherzod Nasrullaev','player'),
('UZB5','UZB','Uzbekistan',45,5,'Umar Eshmurodov','player'),
('UZB6','UZB','Uzbekistan',45,6,'Husniddin Aliqulov','player'),
('UZB7','UZB','Uzbekistan',45,7,'Rustamjon Ashurmatov','player'),
('UZB8','UZB','Uzbekistan',45,8,'Khojiakbar Alijonov','player'),
('UZB9','UZB','Uzbekistan',45,9,'Abdukodir Khusanov','player'),
('UZB10','UZB','Uzbekistan',45,10,'Odiljon Hamrobekov','player'),
('UZB11','UZB','Uzbekistan',45,11,'Otabek Shukurov','player'),
('UZB12','UZB','Uzbekistan',45,12,'Jamshid Iskanderov','player'),
('UZB13','UZB','Uzbekistan',45,13,'Team Photo','photo'),
('UZB14','UZB','Uzbekistan',45,14,'Azizbek Turgunboev','player'),
('UZB15','UZB','Uzbekistan',45,15,'Khojimat Erkinov','player'),
('UZB16','UZB','Uzbekistan',45,16,'Eldor Shomurodov','player'),
('UZB17','UZB','Uzbekistan',45,17,'Oston Urunov','player'),
('UZB18','UZB','Uzbekistan',45,18,'Jaloliddin Masharipov','player'),
('UZB19','UZB','Uzbekistan',45,19,'Igor Sergeev','player'),
('UZB20','UZB','Uzbekistan',45,20,'Abbosbek Fayzullaev','player'),
('COL1','COL','Colombia',46,1,'Emblem','crest'),
('COL2','COL','Colombia',46,2,'Camilo Vargas','player'),
('COL3','COL','Colombia',46,3,'David Ospina','player'),
('COL4','COL','Colombia',46,4,'Dávinson Sánchez','player'),
('COL5','COL','Colombia',46,5,'Yerry Mina','player'),
('COL6','COL','Colombia',46,6,'Daniel Munoz','player'),
('COL7','COL','Colombia',46,7,'Johan Mojica','player'),
('COL8','COL','Colombia',46,8,'Jhon Lucumí','player'),
('COL9','COL','Colombia',46,9,'Santiago Arias','player'),
('COL10','COL','Colombia',46,10,'Jefferson Lerma','player'),
('COL11','COL','Colombia',46,11,'Kevin Castaño','player'),
('COL12','COL','Colombia',46,12,'Richard Rios','player'),
('COL13','COL','Colombia',46,13,'Team Photo','photo'),
('COL14','COL','Colombia',46,14,'James Rodriguez','player'),
('COL15','COL','Colombia',46,15,'Juan Fernando Quintero','player'),
('COL16','COL','Colombia',46,16,'Jorge Carrascal','player'),
('COL17','COL','Colombia',46,17,'Jhon Arias','player'),
('COL18','COL','Colombia',46,18,'Jhon Cordova','player'),
('COL19','COL','Colombia',46,19,'Luis Suarez','player'),
('COL20','COL','Colombia',46,20,'Luis Diaz','player'),
('ENG1','ENG','England',47,1,'Emblem','crest'),
('ENG2','ENG','England',47,2,'Jordan Pickford','player'),
('ENG3','ENG','England',47,3,'John Stones','player'),
('ENG4','ENG','England',47,4,'Marc Guéhi','player'),
('ENG5','ENG','England',47,5,'Ezri Konsa','player'),
('ENG6','ENG','England',47,6,'Trent Alexander-Arnold','player'),
('ENG7','ENG','England',47,7,'Reece James','player'),
('ENG8','ENG','England',47,8,'Dan Burn','player'),
('ENG9','ENG','England',47,9,'Jordan Henderson','player'),
('ENG10','ENG','England',47,10,'Declan Rice','player'),
('ENG11','ENG','England',47,11,'Jude Bellingham','player'),
('ENG12','ENG','England',47,12,'Cole Palmer','player'),
('ENG13','ENG','England',47,13,'Team Photo','photo'),
('ENG14','ENG','England',47,14,'Morgan Rogers','player'),
('ENG15','ENG','England',47,15,'Anthony Gordon','player'),
('ENG16','ENG','England',47,16,'Phil Foden','player'),
('ENG17','ENG','England',47,17,'Bukayo Saka','player'),
('ENG18','ENG','England',47,18,'Harry Kane','player'),
('ENG19','ENG','England',47,19,'Marcus Rashford','player'),
('ENG20','ENG','England',47,20,'Ollie Watkins','player'),
('CRO1','CRO','Croatia',48,1,'Emblem','crest'),
('CRO2','CRO','Croatia',48,2,'Dominik Livaković','player'),
('CRO3','CRO','Croatia',48,3,'Duje Caleta-Car','player'),
('CRO4','CRO','Croatia',48,4,'Josko Gvardiol','player'),
('CRO5','CRO','Croatia',48,5,'Josip Stanišić','player'),
('CRO6','CRO','Croatia',48,6,'Luka Vušković','player'),
('CRO7','CRO','Croatia',48,7,'Josip Sutalo','player'),
('CRO8','CRO','Croatia',48,8,'Kristijan Jakic','player'),
('CRO9','CRO','Croatia',48,9,'Luka Modrić','player'),
('CRO10','CRO','Croatia',48,10,'Mateo Kovacic','player'),
('CRO11','CRO','Croatia',48,11,'Martin Baturina','player'),
('CRO12','CRO','Croatia',48,12,'Lovro Majer','player'),
('CRO13','CRO','Croatia',48,13,'Team Photo','photo'),
('CRO14','CRO','Croatia',48,14,'Mario Pasalic','player'),
('CRO15','CRO','Croatia',48,15,'Petar Sucic','player'),
('CRO16','CRO','Croatia',48,16,'Ivan Perišić','player'),
('CRO17','CRO','Croatia',48,17,'Marco Pasalic','player'),
('CRO18','CRO','Croatia',48,18,'Ante Budimir','player'),
('CRO19','CRO','Croatia',48,19,'Andrej Kramarić','player'),
('CRO20','CRO','Croatia',48,20,'Franjo Ivanovic','player'),
('GHA1','GHA','Ghana',49,1,'Emblem','crest'),
('GHA2','GHA','Ghana',49,2,'Lawrence Ati Zigi','player'),
('GHA3','GHA','Ghana',49,3,'Tariq Lamptey','player'),
('GHA4','GHA','Ghana',49,4,'Mohammed Salisu','player'),
('GHA5','GHA','Ghana',49,5,'Alidu Seidu','player'),
('GHA6','GHA','Ghana',49,6,'Alexander Djiku','player'),
('GHA7','GHA','Ghana',49,7,'Gideon Mensah','player'),
('GHA8','GHA','Ghana',49,8,'Caleb Yirenkyi','player'),
('GHA9','GHA','Ghana',49,9,'Abdul Issahaku Fatawu','player'),
('GHA10','GHA','Ghana',49,10,'Thomas Partey','player'),
('GHA11','GHA','Ghana',49,11,'Salis Abdul Samed','player'),
('GHA12','GHA','Ghana',49,12,'Kamaldeen Sulemana','player'),
('GHA13','GHA','Ghana',49,13,'Team Photo','photo'),
('GHA14','GHA','Ghana',49,14,'Mohammed Kudus','player'),
('GHA15','GHA','Ghana',49,15,'Inaki Williams','player'),
('GHA16','GHA','Ghana',49,16,'Jordan Ayew','player'),
('GHA17','GHA','Ghana',49,17,'André Ayew','player'),
('GHA18','GHA','Ghana',49,18,'Joseph Paintsil','player'),
('GHA19','GHA','Ghana',49,19,'Osman Bukari','player'),
('GHA20','GHA','Ghana',49,20,'Antoine Semenyo','player'),
('PAN1','PAN','Panama',50,1,'Emblem','crest'),
('PAN2','PAN','Panama',50,2,'Orlando Mosquera','player'),
('PAN3','PAN','Panama',50,3,'Luis Mejia','player'),
('PAN4','PAN','Panama',50,4,'Fidel Escobar','player'),
('PAN5','PAN','Panama',50,5,'Andres Andrade','player'),
('PAN6','PAN','Panama',50,6,'Michael Amir Murillo','player'),
('PAN7','PAN','Panama',50,7,'Eric Davis','player'),
('PAN8','PAN','Panama',50,8,'Jose Cordoba','player'),
('PAN9','PAN','Panama',50,9,'Cesar Blackman','player'),
('PAN10','PAN','Panama',50,10,'Cristian Martinez','player'),
('PAN11','PAN','Panama',50,11,'Aníbal Godoy','player'),
('PAN12','PAN','Panama',50,12,'Adalberto Carrasquilla','player'),
('PAN13','PAN','Panama',50,13,'Team Photo','photo'),
('PAN14','PAN','Panama',50,14,'Édgar Bárcenas','player'),
('PAN15','PAN','Panama',50,15,'Carlos Harvey','player'),
('PAN16','PAN','Panama',50,16,'Ismael Díaz','player'),
('PAN17','PAN','Panama',50,17,'Jose Fajardo','player'),
('PAN18','PAN','Panama',50,18,'Cecilio Waterman','player'),
('PAN19','PAN','Panama',50,19,'Jose Luiz Rodriguez','player'),
('PAN20','PAN','Panama',50,20,'Alberto Quintero','player'),
('CC-EU1','CC','Coca-Cola (EU)',51,1,'Lamine Yamal','coke'),
('CC-EU2','CC','Coca-Cola (EU)',51,2,'Joshua Kimmich','coke'),
('CC-EU3','CC','Coca-Cola (EU)',51,3,'Eduardo Camavinga','coke'),
('CC-EU4','CC','Coca-Cola (EU)',51,4,'Josko Gvardiol','coke'),
('CC-EU5','CC','Coca-Cola (EU)',51,5,'Federico Valverde','coke'),
('CC-EU6','CC','Coca-Cola (EU)',51,6,'Virgil van Dijk','coke'),
('CC-EU7','CC','Coca-Cola (EU)',51,7,'Alphonso Davies','coke'),
('CC-EU8','CC','Coca-Cola (EU)',51,8,'Raúl Jiménez','coke'),
('CC-EU9','CC','Coca-Cola (EU)',51,9,'William Saliba','coke'),
('CC-EU10','CC','Coca-Cola (EU)',51,10,'Lautaro Martínez','coke'),
('CC-EU11','CC','Coca-Cola (EU)',51,11,'Harry Kane','coke'),
('CC-EU12','CC','Coca-Cola (EU)',51,12,'Antonee Robinson','coke')
on conflict (id) do nothing;
